### ISSUE TITLE
phantom.js script fails with errors

### ISSUE THREAD

**Issue by leoi11** [BertLo/att-family-plan-bill#1]
`phantomjs ~/src/att-family-plan-bill/phantom.js`

gives:

    ReferenceError: Can't find variable: reporting
    
      https://www.att.com/olam/loginAction.olamexecute?actionEvent=redirectToTguardInProgress:669 in global code
    ReferenceError: Can't find variable: isMotionPoint
    
      https://www.att.com/olam/unauth/js/globalnav/tesla.modules.myatt.js:113 in myatt_linkClick
      https://www.att.com/olam/unauth/js/globalnav/tesla.modules.myatt.js:211
    TypeError: undefined is not an object (evaluating 'H.length')
    
      https://www.att.com/olam/js/tealeaf/tealeaf.min.4.0.1607.OLAM.js:9 in d
      https://www.att.com/olam/js/tealeaf/tealeaf.min.4.0.1607.OLAM.js:9 in post
      https://www.att.com/olam/js/tealeaf/tealeaf.min.4.0.1607.OLAM.js:9
      https://www.att.com/olam/js/tealeaf/tealeaf.min.4.0.1607.OLAM.js:9
      https://www.att.com/olam/js/tealeaf/tealeaf.min.4.0.1607.OLAM.js:9 in onerror
    ReferenceError: Can't find variable: reporting
    
      https://www.att.com/olam/IdentitySuccessAction.olamexecute?reportActionEvent=A_LGN_LOGIN_SUB&loginSource=homepage:1994 in global code
    ReferenceError: Can't find variable: reporting
    
      https://www.att.com/olam/viewInterstitialPromo.myworld:1995 in global code
    ReferenceError: Can't find variable: reporting
    
      https://www.att.com/olam/passthroughAction.myworld?actionType=ViewBillDetails:1986 in global code
    ReferenceError: Can't find variable: lpAddVars
    
      https://www.att.com/olam/passthroughAction.myworld?actionType=ViewBillDetails:2752 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/js/billOverviewTab/usageTabWireless.js:1 in global code
    ReferenceError: Can't find variable: loadBillOverviewLinks
    
      https://www.att.com/olam/billUsageTiles.myworld:35 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/billUsageTiles.myworld:54 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/billUsageTiles.myworld:610 in global code
    ReferenceError: Can't find variable: resetSessionTimoutTimer
    
      https://www.att.com/olam/billUsageTiles.myworld:776 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/billUsageTiles.myworld:812 in global code
    ReferenceError: Can't find variable: $
    
      https://www.att.com/olam/billUsageTiles.myworld:990 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/billUsageTiles.myworld:1164 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/billUsageTiles.myworld:5067 in global code
    ReferenceError: Can't find variable: DTMReportingHelper
    
      https://www.att.com/olam/billUsageTiles.myworld:5081 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/billUsageTiles.myworld:5084 in global code
    ReferenceError: Can't find variable: jQuery
    
      https://www.att.com/olam/billUsageTiles.myworld:5107 in global code
    ReferenceError: Can't find variable: renderedChart
    
      https://www.att.com/olam/billUsageTiles.myworld:964 in FC_Rendered
      https://www.att.com/olam/js/reportChart/FusionCharts.HC.js:580

**Comment by BertLo** [comment]
fixed
